# Generated by Django 5.0.1 on 2024-02-16 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankID', models.CharField(max_length=250)),
                ('drugname', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('moleculeType', models.CharField(max_length=250)),
                ('yearOfDrug', models.PositiveIntegerField()),
                ('confirmStatus', models.CharField(max_length=250)),
                ('drugFamily', models.CharField(max_length=250)),
                ('synonyms', models.CharField(max_length=250)),
                ('smiles', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('chemBLReference', models.CharField(default='somereference', max_length=250)),
                ('drugbankReference', models.CharField(default='somereference', max_length=250)),
                ('dailymedReference', models.CharField(default='somereference', max_length=250)),
                ('smiles_image', models.ImageField(blank=True, null=True, upload_to='smilesimages/')),
            ],
        ),
        migrations.CreateModel(
            name='MechanismOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=250)),
                ('targetReceptor', models.CharField(max_length=250)),
                ('humanReceptor', models.CharField(max_length=250)),
                ('links', models.CharField(max_length=250)),
                ('drugbankID', models.ManyToManyField(to='druginfo.druginformation')),
            ],
        ),
        migrations.CreateModel(
            name='useIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicationInfo', models.CharField(max_length=250)),
                ('therapeuticInfo', models.CharField(max_length=250)),
                ('phase', models.PositiveIntegerField()),
                ('references', models.CharField(max_length=250)),
                ('drugbankID', models.ManyToManyField(to='druginfo.druginformation')),
            ],
        ),
    ]
