# Generated by Django 5.0.1 on 2024-02-05 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankID', models.CharField(max_length=250)),
                ('drugname', models.CharField(max_length=250)),
                ('descrption', models.TextField(max_length=2500)),
                ('moleculeType', models.CharField(max_length=250)),
                ('yearOfDrug', models.PositiveIntegerField()),
                ('confirmStatus', models.CharField(max_length=250)),
                ('drugFamily', models.CharField(max_length=250)),
                ('synonyms', models.CharField(max_length=250)),
                ('smiles', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
            ],
        ),
    ]
