# Generated by Django 4.2.10 on 2024-02-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='targetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceEdge', models.CharField(max_length=250)),
                ('percentOfPrediction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pathCount', models.PositiveIntegerField()),
                ('distinctMetaPaths', models.PositiveIntegerField()),
                ('drugbankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druginfo.druginformation')),
            ],
        ),
        migrations.CreateModel(
            name='sourceEdgeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceEdge', models.CharField(max_length=250)),
                ('percentOfPrediction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pathCount', models.PositiveIntegerField()),
                ('distinctMetaPaths', models.PositiveIntegerField()),
                ('drugbankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druginfo.druginformation')),
            ],
        ),
        migrations.CreateModel(
            name='pathContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbosePath', models.CharField(max_length=250)),
                ('length', models.PositiveIntegerField()),
                ('metaPath', models.CharField(max_length=20)),
                ('percentOfDWPC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentOfPrediction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drugbankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druginfo.druginformation')),
            ],
        ),
        migrations.CreateModel(
            name='metapathContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=250)),
                ('length', models.PositiveIntegerField()),
                ('pathCount', models.PositiveIntegerField()),
                ('percentOfPrediction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metaPath', models.CharField(max_length=250)),
                ('drugbankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druginfo.druginformation')),
            ],
        ),
    ]
