# Generated by Django 5.0.1 on 2024-02-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginformation',
            old_name='descrption',
            new_name='description',
        ),
    ]
