# Generated by Django 5.0.1 on 2024-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0002_rename_descrption_druginformation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginformation',
            name='chemBLReference',
            field=models.CharField(default='somereference', max_length=250),
        ),
        migrations.AddField(
            model_name='druginformation',
            name='dailymedReference',
            field=models.CharField(default='somereference', max_length=250),
        ),
        migrations.AddField(
            model_name='druginformation',
            name='drugbankReference',
            field=models.CharField(default='somereference', max_length=250),
        ),
        migrations.AddField(
            model_name='druginformation',
            name='smiles_image',
            field=models.ImageField(blank=True, null=True, upload_to='smilesimages/'),
        ),
        migrations.CreateModel(
            name='MechanismOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=250)),
                ('targetReceptor', models.CharField(max_length=250)),
                ('humanReceptor', models.CharField(max_length=250)),
                ('links', models.CharField(max_length=250)),
                ('drugbankID', models.ManyToManyField(to='druginfo.druginformation')),
            ],
        ),
    ]
