# Generated by Django 4.2.10 on 2024-02-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0002_targetedge_sourceedgecontribution_pathcontribution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetedge',
            old_name='sourceEdge',
            new_name='targetEdge',
        ),
    ]
