# Generated by Django 5.0.1 on 2024-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0003_druginformation_chemblreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='useIndications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicationInfo', models.CharField(max_length=250)),
                ('therapeuticInfo', models.CharField(max_length=250)),
                ('phase', models.PositiveIntegerField()),
                ('references', models.CharField(max_length=250)),
                ('drugbankID', models.ManyToManyField(to='druginfo.druginformation')),
            ],
        ),
    ]
