# Generated by Django 5.0.1 on 2024-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druginfo', '0004_useindications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useIndications',
            new_name='useIndication',
        ),
    ]
